# Generated by Django 6.1.1 on 2026-09-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_brand_brand_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='category_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
