# Generated by Django 6.1.1 on 2026-09-21 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_brand_brand_alter_product_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.brand'),
            preserve_default=False,
        ),
    ]
